name: pickndream
description: "PicknDream - Réservation d'hôtels avec abonnement"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_paypal_payment: ^1.0.8
  flutter_stripe: ^10.1.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
